version: '3'

services:

  postgres:
    hostname: db
    container_name: lnpp_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - lnpp_db_data:/var/lib/postgresql/data
    ports:
      # To connect to the DB use the HOST_DB_PORT var; 5432 refers to port inside container
      - ${HOST_DB_PORT}:5432

  php:
    hostname: symfony
    container_name: lnpp
    build: 
      context: .
    links:
      - postgres:db
    volumes:
      - ../:/var/www/html/zing
    depends_on:
      - postgres
    ports:
      - ${HOST_PHP_FPM_PORT}:9000

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      # if you want a seamless experience set this to 80, otherwise setting the port explicitly on host's browser will be necessary
      - ${HOST_APP_PORT}:80
      - ${HOST_SECURE_APP_PORT}:443
    volumes:
      - ../:/var/www/html/zing
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
volumes:
  lnpp_db_data:
