version: '3'

# PRPLM Dev Stack
# Includes Php, Redis, Postgres and powered by Linux... also Mailhog
services:
  database:
    hostname: postgres
    container_name: ${APP_NAME}_database
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.build/postgres:/docker-entrypoint-initdb.d
      - prplm_postgres:/var/lib/postgresql/data
    ports:
      - ${HOST_DB_PORT}:5432

  php:
    hostname: php
    container_name: ${APP_NAME}
    build: .
    restart: always
    links:
      - database:postgres
    volumes:
      - ../:/home/zing/dev
      - prplm_logs:/home/zing/logs
    depends_on:
      - database
    ports:
      # if you want a seamless experience set host ports to 80 and 443, otherwise
      # setting the port explicitly on host's browser will be necessary
      - ${HOST_APP_PORT}:80
      - ${HOST_SECURE_APP_PORT}:443

  email_server:
    hostname: mailhog
    container_name: ${APP_NAME}_mail_server
    image: mailhog/mailhog:latest
    ports:
      - ${HOST_MAIL_SMTP_PORT}:1025
      - ${HOST_MAIL_WEB_PORT}:8025

  cache:
    hostname: redis
    container_name: ${APP_NAME}_cache
    image: redis:7.0.5-alpine
    ports:
      - ${HOST_CACHE_PORT}:6379
    volumes:
      - prplm_redis:/var/lib/redis/data
volumes:
  prplm_postgres:
  prplm_redis:
  prplm_logs:
