CREATE DATABASE zing;
CREATE USER zing WITH PASSWORD 'containerdev123';
GRANT ALL PRIVILEGES ON DATABASE zing TO zing;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    TO zing;

CREATE DATABASE zing_test;
CREATE USER zing_test WITH ENCRYPTED PASSWORD 'containertest123';
GRANT ALL PRIVILEGES ON DATABASE zing_test TO zing_test;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    TO zing_test;
